language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - coverage run --source=shop_navigator_app -m pytest tests/views_test/
after_success:
  - coveralls